{% set name = "gmatnonlinearelastic" %}
{% set version = "0.2.0" %}
{% set sha256 = "e46aeae19c29e81481ace56f85b0e0c20d0edd1241b2f03938bba80f73d837f7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatNonLinearElastic/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
    - gmattensor
  run:
    - xtensor
    - gmattensor

test:
  commands:
    - test -d ${PREFIX}/include/GMatNonLinearElastic  # [unix]
    - test -f ${PREFIX}/include/GMatNonLinearElastic/Cartesian3d.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/GMatNonLinearElastic/GMatNonLinearElasticConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GMatNonLinearElastic\Cartesian3d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\GMatNonLinearElasticConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/GMatNonLinearElastic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Non-linear elastic material model (C++ header-only library).
  description: Non-linear elastic material model (C++ header-only library).
  doc_url: https://github.com/tdegeus/GMatNonLinearElastic
  dev_url: https://github.com/tdegeus/GMatNonLinearElastic

extra:
  recipe-maintainers:
    - tdegeus
